version: '3'

services:
  db:
    container_name: 'db-coletor'
    image: postgres
    environment:
      - POSTGRES_USER=coletor
      - POSTGRES_PASSWORD=Mapcwd789
      - POSTGRES_DB=coletor
    ports:
      - "5432:5432"

  web:
    restart: always
    container_name: 'coletor'
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/code
    depends_on:
      - db
    ports:
    - "8000:8000"
