# Generated by Django 3.0.8 on 2020-07-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColetor', '0003_auto_20200730_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coletores',
            old_name='coletor',
            new_name='codigo',
        ),
    ]
