# Generated by Django 3.0.8 on 2020-07-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColetor', '0004_auto_20200730_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cadastropessoa',
            unique_together={('cracha',)},
        ),
    ]
