# Generated by Django 3.0.8 on 2020-07-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColetor', '0005_auto_20200730_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cadastropessoa',
            unique_together=set(),
        ),
    ]
